name: Build and Publish Docker Image

on:
  push:
    branches:
      - master # Запускать workflow при пуше в ветку main
  pull_request:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Проверка репозитория
      - name: Checkout repository
        uses: actions/checkout@v3

      # Шаг 2: Логин в GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      # Шаг 3: Сборка и публикация Docker-образа
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/anemcov/ge-lic-bot:latest
